// gui/src/components/Navigation/index.vue
<template>
  <div class="navigation custom-scroll">
    <NavigationItem
      v-for="o of options"
      :key="o.name"
      :name="o.name"
      :selected="isSelected(o.name)"
    />
  </div>
</template>

<script>
  import NavigationItem from './NavigationItem.vue'

  export default {
    components: { NavigationItem },
    props: {
      options: { type: Array, default: () => [] },
      path: { type: String, required: true },
    },
    methods: {
      isSelected (path) {
        return this.path.toLowerCase().slice(1) === path.toLowerCase()
      },
    },
  }
</script>

<style lang="scss">
  @import '../../styles/colors.scss';

  .navigation {
    flex-direction: column;
    display: inline-flex;
    position: relative;

    min-width: 200px;
    height: 100%;

    background-color: $neu300;
    transition: all 0.3s ease 0s;
  }
</style>

// gui/src/components/Navigation/index.jsx
import React from 'react'
import NavigationItem from './NavigationItem.jsx'

import './index.scss';

function Navigation ({ options }) {
  return (
    <div className="navigation custom-scroll">
      {options.map((o, index) => 
        <NavigationItem
          key={`navigation-item-${index}`}
          name={o.name}
          selected={window.location.pathname.toLowerCase().slice(1) === o.name.toLowerCase()}
        />
      )}
    </div>
  );
}

export default Navigation
