// gui/src/components/Layout/index.jsx
import React from 'react'
import { Switch, Route, Router } from 'react-router-dom'

import Home from '../../pages/home'
import { Navigation } from '../index.js'

import './index.scss';

function Layout ({ pages, options }) {
  return (
    <div className="layout">
      <Navigation options={options} />
      <div className="layout__page custom-scroll">
        <Switch>
          <Route  component={ Home }/>
        </Switch>
      </div>
    </div>
  );
}

export default Layout

// gui/src/components/Layout/index.vue
<template>
  <div class="layout">
    <Navigation
      :options="options"
      :path="$route.path"
    />
    <div class="layout__page custom-scroll">
      <router-view />
    </div>
  </div>
</template>

<style lang="scss">
  @import '../../styles/index.scss';
  @import '../../styles/colors.scss';

  .layout {
    display: flex;
    width: 100%;
    height: 100%;

    &__page {
      flex: 1;
      display: flex;

      min-width: 0;
      min-height: 0;

      padding: 20px;
      box-sizing: border-box;

      background-color: $sec100;
    }
  }
</style>

<script>
  export default {
    mounted () {
      console.log(this.$route)
    },
    props: {
      options: { type: Array, default: () => [] }
    }
  }
</script>
